"""add bedolaga sync tables

Revision ID: 0991c979a5f8
Revises: 6d2d497a11f9
Create Date: 2026-07-30 22:37:13.257940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0991c979a5f8'
down_revision: Union[str, Sequence[str], None] = '6d2d497a11f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bedolaga_subscription_daily',
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_trial', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'status', 'is_trial')
    )
    op.create_table('bedolaga_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('actual_status', sa.Text(), nullable=False),
    sa.Column('is_trial', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=False),
    sa.Column('end_date', sa.Text(), nullable=False),
    sa.Column('traffic_limit_gb', sa.Float(), nullable=False),
    sa.Column('traffic_used_gb', sa.Float(), nullable=False),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('autopay_enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bedolaga_transactions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('amount_kopeks', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bedolaga_users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('has_had_paid_subscription', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bedolaga_users')
    op.drop_table('bedolaga_transactions')
    op.drop_table('bedolaga_subscriptions')
    op.drop_table('bedolaga_subscription_daily')
    # ### end Alembic commands ###
