"""add asset description

Revision ID: 0d23a6383b34
Revises: 0991c979a5f8
Create Date: 2026-07-31 15:28:04.211732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d23a6383b34'
down_revision: Union[str, Sequence[str], None] = '0991c979a5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='' (not autogenerated) — SQLite refuses to add a NOT
    # NULL column with no default to a table that already has rows, which
    # every real deployment's `assets` table does.
    op.add_column('assets', sa.Column('description', sa.Text(), nullable=False, server_default=''))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'description')
    # ### end Alembic commands ###
